# Generated by Django 4.2.6 on 2023-11-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LecturasSensor',
            fields=[
                ('idlectura', models.AutoField(primary_key=True, serialize=False)),
                ('nombreusu', models.CharField(max_length=45)),
                ('pulso', models.PositiveSmallIntegerField()),
                ('oxigeno', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosSensor',
            fields=[
                ('idsensor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreusu', models.CharField(max_length=45)),
                ('newrpm', models.IntegerField()),
                ('newoxygen', models.IntegerField()),
                ('lastupdate', models.DateTimeField()),
            ],
        ),
    ]
