# Generated by Django 4.2.5 on 2023-10-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocedorEmociones', '0002_alter_emocionesusuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='emocionesusuario',
            name='nombre_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
