# Generated by Django 4.2.6 on 2023-11-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocedorEmociones', '0003_emocionesusuario_nombre_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='emocionesusuario',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
